[package]
name = "isa_minimization"
version = "0.1.0"
edition = "2024"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
pedantic = "warn"
unwrap_used = "deny"

[dependencies]
rhai = "1"
regex = "1"
liberty-db = "0.17"
pest = "2.8"
pest_derive = "2.8"
thiserror = "2"
petgraph = "0.8.3"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "simulate"
harness = false