[package]
name = "isa_minimization"
version = "0.1.0"
edition = "2024"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
pedantic = "warn"
unwrap_used = "deny"

[dependencies]
rhai = "1"
regex = "1"
liberty-db = "0.17"
pest = "2.8"
pest_derive = "2.8"
thiserror = "2"
petgraph = "0.8.3"
oxidd = "0.11.0"
itertools = "0.15.0"
rand = "0.10.2"
z3 = { version = "0.20", features = ["bundled"] }

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "simulate"
harness = false

[[bench]]
name = "generate_candidates"
harness = false
